
package br.superdia.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidateCardService", targetNamespace = "http://webservice.superdia.br/", wsdlLocation = "http://localhost:8080/ValidateCardService/ValidateCard?wsdl")
public class ValidateCardService
    extends Service
{

    private final static URL VALIDATECARDSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDATECARDSERVICE_EXCEPTION;
    private final static QName VALIDATECARDSERVICE_QNAME = new QName("http://webservice.superdia.br/", "ValidateCardService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ValidateCardService/ValidateCard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDATECARDSERVICE_WSDL_LOCATION = url;
        VALIDATECARDSERVICE_EXCEPTION = e;
    }

    public ValidateCardService() {
        super(__getWsdlLocation(), VALIDATECARDSERVICE_QNAME);
    }

    public ValidateCardService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDATECARDSERVICE_QNAME, features);
    }

    public ValidateCardService(URL wsdlLocation) {
        super(wsdlLocation, VALIDATECARDSERVICE_QNAME);
    }

    public ValidateCardService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDATECARDSERVICE_QNAME, features);
    }

    public ValidateCardService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidateCardService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidateCard
     */
    @WebEndpoint(name = "ValidateCardPort")
    public ValidateCard getValidateCardPort() {
        return super.getPort(new QName("http://webservice.superdia.br/", "ValidateCardPort"), ValidateCard.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidateCard
     */
    @WebEndpoint(name = "ValidateCardPort")
    public ValidateCard getValidateCardPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.superdia.br/", "ValidateCardPort"), ValidateCard.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDATECARDSERVICE_EXCEPTION!= null) {
            throw VALIDATECARDSERVICE_EXCEPTION;
        }
        return VALIDATECARDSERVICE_WSDL_LOCATION;
    }

}
